### ISSUE TITLE
Expert Issue:  Asynchronous call in sequence ? with function return.  

### ISSUE THREAD

**Issue by tejastank** [datagraph/jquery-jsonrpc#19]
function  test_snippetbucket(model,method, args){
        
        var dfd = $.Deferred();
        var res = {};
        var self = this;
        $('#loader').show(0);
 
        
        $.jsonRPC.request('xmatrix', {
            async: true,
            params : [["tta","exp","oem", model, method, args]],
            success : function(data) {
                res = data.result;
                $('#loader').hide();
                dfd.resolve( res );
            },
            error : function(data) {
                res = data.result;
                $('#loader').hide();
                dfd.resolve( res );
            }
        });
     
        dfd.promise();
        return res;
    },

My synchronous call working great.

when I try to manage Asynchronous call, it not in sequence.

to manage it in sequence like syncronious, how does I do ?
I try $.differed but even did not work.

expert advice needed, please developers share your right flow to do this way.

Also synchronous call block ui, so looking for perfect code to resolve with function return in sequence.

**Comment by lucifurious** [comment]
I'm sorry I didn't see this before.

If you haven't figured it out yet, you need to set `"async": false` instead of `"async": true`.

**Comment by tejastank** [comment]
thanks for response, but I had resolve.
