### ISSUE TITLE
Does this library aim to be standards-compliant?

### ISSUE THREAD

**Issue by x6herbius** [datagraph/jquery-jsonrpc#21]
I'm assuming [this page](http://www.jsonrpc.org/specification) should be considered the authority on how JSON RPC 2.0 communications should be structured. I've noticed that this library doesn't seem to include the required `"jsonrpc": "2.0"` entry in the requests and responses (sometimes using `"version"` instead), and that it will automatically take out any `session` from the provided params and stick it on the main request instead.

Does this technically make the library non-standards-compliant, and were there reasons for this? Does this generally matter in the real works where JSON RPC requests are used? I'm trying to gauge how strictly I should be writing my own server implementation with respect to what the specification says.

**Comment by lisp** [comment]
this library belongs to a time when we thought there would be value to an rpc interface to the service.
as matters have evolved there was not demand.
not the date of the last commit.
the supported interfaces for production use are limited to the w3c rdf/sparql over http recommendations
the only current rpc-like requests are limited to internal operations within the web ui, but that is itself being phased out, to be replaced with a web application which uses a replicated rdf store for the user/account/repository metadata.

**Comment by x6herbius** [comment]
OK, so it's sounding like the library itself is more or less deprecated. That's fine, I'll move forward with that in mind. Thanks!

**Comment by lisp** [comment]
more than that, the api which it would be writing to has been deprecated.

as to the other interfaces, there are several alternative javascript libraries which implement access over the w3c standard protocols.
we cannot offer any real advantage by authoring yet another.
